MSP430UltrasonicLibrary: ussSwLibVFRCalibFlowTemperature.c File Reference
ussSwLibVFRCalibFlowTemperature.c File Reference
#include "ussSwLib.h"
#include "USS_Config/USS_userConfig.h"
Functions
USS_message_code USS_calculateVolumeFlowRate (USS_SW_Library_configuration *config, USS_Algorithms_Results_fixed_point *results)
int32_t USS_getFlow (uint8_t col, uint8_t row, uint8_t numFlows, USS_Algorithms_Quad_Point *pQuadPoints)
int32_t USS_getTemp (uint8_t col, uint8_t row, uint8_t numFlows, USS_Algorithms_Quad_Point *pQuadPoints)
USS_message_code USS_isPtInside (USS_SW_Library_configuration *config, int8_t row, int8_t col, USS_Algorithms_Results_fixed_point *results)
USS_message_code USS_initialSearchQuad (USS_SW_Library_configuration *config, USS_Algorithms_Results_fixed_point *results)
USS_message_code USS_searchNeighborQuad (USS_SW_Library_configuration *config, USS_Algorithms_Results_fixed_point *results)
USS_message_code USS_calibrateVFRFlowTemperature (USS_SW_Library_configuration *config, USS_Algorithms_Results_fixed_point *results)
The following API calibrates Volume Flow Rate using flow and temperature.
Function Documentation
USS_calculateVolumeFlowRate()
USS_message_code USS_calculateVolumeFlowRate (USS_SW_Library_configuration * config, USS_Algorithms_Results_fixed_point * results)
References _USS_SW_Library_configuration_::algorithmsConfig, _USS_Algorithms_User_Configuration_::calibObject, _USS_Alg_volume_Flow_Temperature_Calib_Object_::colNum, _USS_Algorithms_User_Configuration_::flowTempCalibObject, _USS_Algorithms_Quad_Meter_Constant_::iq16M0, _USS_Algorithms_Quad_Meter_Constant_::iq16M1, _USS_Algorithms_Quad_Meter_Constant_::iq16M2, _USS_Algorithms_Quad_Meter_Constant_::iq16M3, _USS_Algorithms_Results_fixed_point_::iq16Temperature, _USS_Algorithms_Results_fixed_point_::iq16VolumeFlowRate, _USS_Algorithms_Results_fixed_point_::iq16VolumeFlowRateNoCalib, _USS_Alg_volume_Flow_Temperature_Calib_Object_::numOfFlows, _USS_Alg_volume_Flow_Temperature_Calib_Object_::pQuadMeterConstants, _USS_Alg_volume_Flow_Temperature_Calib_Object_::rowNum, and USS_message_code_no_error.
Referenced by USS_calibrateVFRFlowTemperature().
USS_getFlow()
int32_t USS_getFlow (uint8_t col, uint8_t row, uint8_t numFlows, USS_Algorithms_Quad_Point * pQuadPoints)
References _USS_Algorithms_Quad_Point_::iq16Flow.
Referenced by USS_initialSearchQuad(), USS_isPtInside(), and USS_searchNeighborQuad().
USS_getTemp()
int32_t USS_getTemp (uint8_t col, uint8_t row, uint8_t numFlows, USS_Algorithms_Quad_Point * pQuadPoints)
References _USS_Algorithms_Quad_Point_::iq16Temp.
Referenced by USS_initialSearchQuad(), USS_isPtInside(), and USS_searchNeighborQuad().
USS_isPtInside()
USS_message_code USS_isPtInside (USS_SW_Library_configuration * config, int8_t row, int8_t col, USS_Algorithms_Results_fixed_point * results)
References _USS_SW_Library_configuration_::algorithmsConfig, _USS_Algorithms_User_Configuration_::calibObject, _USS_Algorithms_User_Configuration_::flowTempCalibObject, _USS_Algorithms_Results_fixed_point_::iq16Temperature, _USS_Algorithms_Results_fixed_point_::iq16VolumeFlowRate, _USS_Alg_volume_Flow_Temperature_Calib_Object_::numOfFlows, _USS_Alg_volume_Flow_Temperature_Calib_Object_::numOfTemps, _USS_Alg_volume_Flow_Temperature_Calib_Object_::pQuadPoints, _USS_Alg_volume_Flow_Temperature_Calib_Object_::searchQuadCount, USS_getFlow(), USS_getTemp(), USS_message_code_Calibration_VFR_pt_inside_quadrilateral, and USS_message_code_Calibration_VFR_pt_outside_quadrilateral.
Referenced by USS_calibrateVFRFlowTemperature(), and USS_searchNeighborQuad().
USS_initialSearchQuad()
USS_message_code USS_initialSearchQuad (USS_SW_Library_configuration * config, USS_Algorithms_Results_fixed_point * results)
References _USS_SW_Library_configuration_::algorithmsConfig, _USS_Algorithms_User_Configuration_::calibObject, _USS_Alg_volume_Flow_Temperature_Calib_Object_::colNum, _USS_Algorithms_User_Configuration_::flowTempCalibObject, _USS_Algorithms_Results_fixed_point_::iq16Temperature, _USS_Algorithms_Results_fixed_point_::iq16VolumeFlowRate, _USS_Alg_volume_Flow_Temperature_Calib_Object_::numOfFlows, _USS_Alg_volume_Flow_Temperature_Calib_Object_::numOfTemps, _USS_Alg_volume_Flow_Temperature_Calib_Object_::pQuadPoints, _USS_Alg_volume_Flow_Temperature_Calib_Object_::rowNum, USS_getFlow(), USS_getTemp(), and USS_message_code_no_error.
Referenced by USS_calibrateVFRFlowTemperature().
USS_searchNeighborQuad()
USS_message_code USS_searchNeighborQuad (USS_SW_Library_configuration * config, USS_Algorithms_Results_fixed_point * results)
References _USS_SW_Library_configuration_::algorithmsConfig, _USS_Algorithms_User_Configuration_::calibObject, _USS_Alg_volume_Flow_Temperature_Calib_Object_::colNum, _USS_Algorithms_User_Configuration_::flowTempCalibObject, _USS_Algorithms_Results_fixed_point_::iq16Temperature, _USS_Algorithms_Results_fixed_point_::iq16VolumeFlowRate, _USS_Alg_volume_Flow_Temperature_Calib_Object_::numOfFlows, _USS_Alg_volume_Flow_Temperature_Calib_Object_::pQuadPoints, _USS_Alg_volume_Flow_Temperature_Calib_Object_::rowNum, USS_getFlow(), USS_getTemp(), USS_isPtInside(), USS_message_code_Calibration_VFR_pt_inside_quadrilateral, and USS_message_code_Calibration_VFR_pt_outside_quadrilateral.
Referenced by USS_calibrateVFRFlowTemperature().
© Copyright 1995-2020, Texas Instruments Incorporated. All rights reserved.
Trademarks | Privacy policy | Terms of use | Terms of sale